// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrzuMQmAz73kDWGHVW42j8dT-xZoE03s',
    appId: '1:771627760712:android:fb169cf532327a3f7fac7d',
    messagingSenderId: '771627760712',
    projectId: 'careerverse-3057',
    storageBucket: 'careerverse-3057.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWuRkEUihVEu11MGt0JMSR8uTxBPiYQU',
    appId: '1:771627760712:ios:84162f2af793b4a47fac7d',
    messagingSenderId: '771627760712',
    projectId: 'careerverse-3057',
    storageBucket: 'careerverse-3057.firebasestorage.app',
    androidClientId: '771627760712-38ss2q9boeu0a1qcdg09papqb534q2ip.apps.googleusercontent.com',
    iosClientId: '771627760712-g3c3923i6c132a5vgo4lv34ln7g58do3.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerverseapp',
  );
}
